Django_Practice/Django_Practice/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Url_pratice/', include('Url_practice.urls')),
    path('dynamic_webpages/', include('dynamic_webpages.urls')),
    path('todolist/', include('loop_practice.urls')),
    path('todo/', include('todo.urls'))
]

Django_Practice/Url_practice/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('hello/<str:name>/', views.greetings, name='greetings'),
]

Django_Practice/dynamic_webpages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("hello/", views.hello, name = 'hello'),
    path("hello/<str:name>/", views.greetings, name = 'greetings'),
    path("birthday_v1", views.birthday_v1, name = "birthdays_v1"),
    path("birthday_v2", views.birthday_v2, name = "birthday_v2")
]

Django_Practice/loop_practice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.todolist, name = "todolist")
]

Django_Practice/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns =[
    path('', views.todo, name = "index"),
    path('today', views.due_task, name = "today")
]

Django_Practice/todo/models.py
from django.db import models

# Create your models here.

Django_Practice/Url_practice/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def hello (request):
    return HttpResponse("Hello, World!")

def greetings(request, name):
    return HttpResponse(f"Hello, {name}!")

Django_Practice/dynamic_webpages/views.py
import time
from django.shortcuts import render


# Create your views here.

#Renders default hello page
def hello (request):
    return render(request, "greetings.html", {
        "name": "World"
    })

#Renders greetings with name
def greetings (request, name):
    return render(request, "greetings.html", {
        "name": name.capitalize()
    })

#Checks if today is 5th April and returns whether today is my birthday or not with conditional logic in views.py
def birthday_v1 (request):
    date = time.ctime().split()
    #Checks if the date is 5th April
    if date[2] == "5" and date[1] == "April":
        return render(request, "birthday_v1.html", {
            "state": "Yes",
            "state_use": ""
        })
    else:
        return render(request, "birthday_v1.html", {
            "state": "No",
            "state_use": "not"
        })
    

#Checks if today is 5th April and returns whether today is my birthday or not with conditional logic in the Html file
def birthday_v2(request):
    date = time.ctime().split()
    return render (request, "birthday_v2.html", {
        "birthday": date[2] == "5" and date[1] == "April"
    })

Django_Practice/loop_practice/views.py
from django.shortcuts import render

# Create your views here.
def todolist(request):
    tasks = ["read", "eat", "sleep"]
    return render(request, "todo.html", {
        "tasks" : tasks
    })

Django_Practice/todo/views.py
from django.shortcuts import render
from dataclasses import dataclass
import datetime 

@dataclass
class task():
    name: str
    date: str
    time: str


Tasks = []

# Create your views here.
def todo (request):
    if request.method == "GET":
        return render (request, 'index.html')
        
    if request.method == "POST":
        new_task = task(request.POST['task'].capitalize(), request.POST['Due-date'], request.POST['Due-time'])
        Tasks.append(new_task)
        return render(request, 'index.html', {
        "Tasks" : Tasks,
        })

def due_task(request):
    Due_Tasks = []
    for task in Tasks:
        date = task.date.split("-")
        today = datetime.date.today()
        if int(date[0]) == int(today.year) and int(date[1]) == int(today.month) and int(date[2]) == int(today.day):
            Due_Tasks.append(task)
    Due_Tasks        
    return render(request, 'today.html', {
        "Due_Tasks" : Due_Tasks
    })

Django_Practice/dynamic_webpages/templates/birthday_v1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> {{state}}, today is {{state_use}} your Birthday. </h1>
</body>
</html>

Django_Practice/dynamic_webpages/templates/birthday_v2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if birthday %}
    <h1> Yes, It is your birthday</h1>
    {% else %}
    <h1> No, It is not your birthday</h1>
    {% endif %}
</body>
</html>

Django_Practice/dynamic_webpages/templates/greetings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello {{name}}</h1>
</body>
</html>

Django_Practice/loop_practice/templates/todo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>You the following activities to complete today</h1>
    <ul>
        {% for task in tasks %}
        <li> {{task}}</li>  
        {% endfor %}

    </ul>

</body>
</html>

Django_Practice/todo/templates/index.html
{% extends "layout.html" %}

{% block body %}

<h1> All Task </h1>
<table style = "margin: 0; border-collapse: collapse">
    <th style = "margin: 0; border: 1px solid black; width: 20em"> Task </th>
    <th style = "margin: 0; border: 1px solid black; width: 20em"> Due Date </th>
    <th style = "margin: 0; border: 1px solid black; width: 20em"> Due Time</th>

        {% for task in Tasks %}
        <tr>
            <td style = "margin: 0; border: 1px solid black; width: 20em">
                {{ task.name }}
            </td>
            <td style = "margin: 0; border: 1px solid black; width: 20em">
                {{ task.date }}
            </td>
            <td style = "margin: 0; border: 1px solid black; width: 20em">
                {{ task.time }}
            </td>
            
        </tr>
        {% endfor %}
</table>

{% endblock %}

Django_Practice/todo/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> To do </title>
</head>
<body>
    {% block body %}
    {% endblock %}

    <h1> Add Task </h1>
    <form action="{% url 'todo:index' %}" method = "post">
        <span>
            {% csrf_token %} 
            <input type="text" name="task" required>
            <input type="date" name="Due-date">
            <input type="time" name="Due-time">
            <input type="submit" value="Add Task">
        </span>
    </form>
    <ul>
        <li> <a href="{% url 'todo:index' %}"> Home </a></li>
        <li> <a href="{% url 'todo:today' %}"> Due Task </a></li>
    </ul>
</body>
</html>

Django_Practice/todo/templates/today.html
{% extends "layout.html" %}

{% block body %}

<h1> Due Task </h1>
<table style = "margin: 0; border-collapse: collapse">
    <th style = "margin: 0; border: 1px solid black; width: 20em"> Task </th>
    <th style = "margin: 0; border: 1px solid black; width: 20em"> Due Date </th>
    <th style = "margin: 0; border: 1px solid black; width: 20em"> Due Time</th>

        {% for task in Due_Tasks %}
        <tr>
            <td style = "margin: 0; border: 1px solid black; width: 20em">
                {{ task.name }}
            </td>
            <td style = "margin: 0; border: 1px solid black; width: 20em">
                {{ task.date }}
            </td>
            <td style = "margin: 0; border: 1px solid black; width: 20em">
                {{ task.time }}
            </td>
            
        </tr>
        {% endfor %}
</table>

{% endblock %}